version: '3.8'

services:
  frontend:
    image: gymapp-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
