# Generated by Django 5.1.2 on 2024-10-21 08:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='bodypart',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('user', 'date')},
        ),
    ]
