# Generated by Django 5.1.2 on 2024-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_workoutexercise_workout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutDay',
            new_name='Workout',
        ),
    ]
