# Generated by Django 5.1.2 on 2024-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_rename_workoutday_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='body_parts',
            field=models.ManyToManyField(blank=True, related_name='workout_days', to='gym.bodypart'),
        ),
    ]
