# Generated by Django 5.1.2 on 2024-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_workout_body_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutset',
            old_name='workout_day',
            new_name='workout',
        ),
        migrations.AlterField(
            model_name='workout',
            name='body_parts',
            field=models.ManyToManyField(blank=True, related_name='workout', to='gym.bodypart'),
        ),
    ]
