# Generated by Django 5.1.2 on 2024-10-15 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_workout_day_workoutset_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
