# Generated by Django 5.1.2 on 2024-10-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_workout_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together={('workout', 'exercise')},
        ),
    ]
