# Generated by Django 5.1.2 on 2024-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_workoutset_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
