# Generated by Django 5.1.2 on 2024-10-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_workoutset_reps_alter_workoutset_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutset',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutset',
            name='weight',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='gym.workoutset')),
            ],
        ),
    ]
