# Generated by Django 5.1.2 on 2024-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_remove_workoutset_reps_remove_workoutset_weight_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
